name: build not-kernel CI variant r8q

on:
    push:
       branches: [ "main" ]
    workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    env:
      DEVICE: r8q
      DEVICE_NAME: Galaxy S20 FE
      KERNEL_NAME: not_kernel

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set Build Start Time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Set Build End Time
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate Build Duration
        run: |
          duration=$((END_TIME - START_TIME))
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          echo "BUILD_DURATION=${minutes}m ${seconds}s" >> $GITHUB_ENV

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Kernel-r8q
          path: not-CI-*.zip
